# base image
FROM arm32v7/python:3.7.0-stretch

# install tools to add apt-repository
RUN apt-get update && \
    apt-get -y install netcat devscripts build-essential && \
    apt-get clean

# add Snap7 library
 RUN add-apt-repository ppa:gijzelaar/snap7 && \
     apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CAFC44EE7F39098CE6EC229CCA70E6A9087475A0 && \
     sed -i 's/cosmic/yakkety/g' /etc/apt/sources.list.d/gijzelaar-ubuntu-snap7-cosmic.list && \
     apt-get update && \
     apt-get -y install libsnap7-dev

# set working directory
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint-prod.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint-prod.sh
RUN chmod +x /usr/src/app/entrypoint-prod.sh

# add app
COPY . /usr/src/app

# run server
CMD ["/usr/src/app/entrypoint-prod.sh"]