# base image
FROM arm32v7/python:3.7.0-stretch

# install tools to add apt-repository
RUN apt-get update && \
    apt-get -y install devscripts build-essential && \
    apt-get clean

RUN wget -O snap7-iot-arm-1.4.2.tar.gz https://sourceforge.net/projects/snap7/files/Snap7-IoT/snap7-iot-arm/snap7-iot-arm-1.4.2.tar.gz/download
RUN tar -zxvf snap7-iot-arm-1.4.2.tar.gz
RUN cd snap7-iot-arm-1.4.2/build/unix/ && make -f arm_v7_linux.mk all && \
    cp ../bin/arm_v7-linux/libsnap7.so /usr/lib/libsnap7.so && \
    cp ../bin/arm_v7-linux/libsnap7.so /usr/local/lib/libsnap7.so


# RUN echo "deb-src http://ppa.launchpad.net/gijzelaar/snap7/ubuntu yakkety main " > /etc/apt/sources.list.d/snap7.list
# RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CAFC44EE7F39098CE6EC229CCA70E6A9087475A0 
# RUN apt-get update
# RUN apt-get source --build snap7

# add Snap7 Library; create a FrankenDebian :)
# Replace cosmic (Debian) with yakkety (Ubuntu) release to force package install
# See http://www.webupd8.org/2014/10/how-to-add-launchpad-ppas-in-debian-via.html
# RUN add-apt-repository ppa:gijzelaar/snap7 && \
#     apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CAFC44EE7F39098CE6EC229CCA70E6A9087475A0 && \
#     sed -i 's/cosmic/yakkety/g' /etc/apt/sources.list.d/gijzelaar-ubuntu-snap7-cosmic.list && \
#     apt-get update && \
#     apt-get -y install libsnap7-dev

# set working directory
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app

# run server
CMD ["/usr/src/app/entrypoint.sh"]