# base image
FROM arm32v7/python:3.7.0-stretch

# install tools to add apt-repository
RUN apt-get update
RUN apt-get -y install netcat
RUN apt-get -y install build-essential
RUN apt-get clean

RUN wget -O snap7-iot-arm-1.4.2.tar.gz https://sourceforge.net/projects/snap7/files/Snap7-IoT/snap7-iot-arm/snap7-iot-arm-1.4.2.tar.gz/download
RUN tar -zxvf snap7-iot-arm-1.4.2.tar.gz
RUN cd snap7-iot-arm-1.4.2/build/unix/ && make -f arm_v7_linux.mk all && \
    cp ../bin/arm_v7-linux/libsnap7.so /usr/lib/libsnap7.so && \
    cp ../bin/arm_v7-linux/libsnap7.so /usr/local/lib/libsnap7.so && \
    ldconfig

# set working directory
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app

# run server
CMD ["/usr/src/app/entrypoint.sh"]