# base image
FROM python:3.6.5-slim

# install netcat and tools to add apt-repository
RUN apt-get update && \
    apt-get -y install netcat software-properties-common && \
    apt-get clean

# add Snap7 Library
# Replace cosmic (Ubuntu) with bionic (Debian) release to force package install
# See http://www.webupd8.org/2014/10/how-to-add-launchpad-ppas-in-debian-via.html
RUN add-apt-repository ppa:gijzelaar/snap7 && \
      sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/gijzelaar-ubuntu-snap7-cosmic.list && \
      apt-get update && \
      apt-get -y --allow-unauthenticated install libsnap7-dev

# set working directory
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app

# run server
CMD ["/usr/src/app/entrypoint.sh"]